#ifndef OPTIONS_H
#define OPTIONS_H

#define EXTRA_DIRECTION_SMOOTH 0.9
#define EXTRA_VELOCITY_SMOOTH 0.9
#define EXTRA_STRAFE_SMOOTH 0.9
#define EXTRA_CROUCHED_SMOOTH 0.9
#define EXTRA_GAIT_SMOOTH 0.1
#define EXTRA_JOINT_SMOOTH 0.5

#endif // !OPTION_H
